/**
 * 文件说明: 定义天气筛选 Dock 和筛选浮层共享的中英文文案。
 * 对应文档: docs/prototypes/weather-filter-interaction/index.html
 */

export const filterCopy = {
  zh: {
    region: '地区',
    subRegion: '省份',
    time: '时间',
    nextDays: (days: number) => `${days}天`,
    date: '日期',
    layer: '图层',
    quickFilters: '推荐',
    temperature: '气温',
    weather: '天气',
    humidity: '湿度',
    precipitation: '降水',
    wind: '风速',
    elevation: '海拔',
    all: '全部',
    off: '不限',
    enabled: '启用',
    reset: '重置',
    done: '完成',
    minTemperature: '最低温度',
    maxTemperature: '最高温度',
    minHumidity: '最低湿度',
    maxHumidity: '最高湿度',
    minPrecipitation: '最低降水',
    maxPrecipitation: '最高降水',
    minWind: '最低风速',
    maxWind: '最高风速',
    minElevation: '最低海拔',
    maxElevation: '最高海拔',
    comfortHelp: '舒适度按气温 42%、天气 28%、湿度 20% 和基础分 10% 计算，并扣除降水和最大风速；分数越高越适合户外活动。'
  },
  en: {
    region: 'Region',
    subRegion: 'Province',
    time: 'Time',
    nextDays: (days: number) => `${days}d`,
    date: 'Date',
    layer: 'Layer',
    quickFilters: 'Suggested',
    temperature: 'Temperature',
    weather: 'Weather',
    humidity: 'Humidity',
    precipitation: 'Rainfall',
    wind: 'Wind',
    elevation: 'Elevation',
    all: 'All',
    off: 'Any',
    enabled: 'Enable',
    reset: 'Reset',
    done: 'Done',
    minTemperature: 'Minimum temperature',
    maxTemperature: 'Maximum temperature',
    minHumidity: 'Minimum humidity',
    maxHumidity: 'Maximum humidity',
    minPrecipitation: 'Minimum rainfall',
    maxPrecipitation: 'Maximum rainfall',
    minWind: 'Minimum wind',
    maxWind: 'Maximum wind',
    minElevation: 'Minimum elevation',
    maxElevation: 'Maximum elevation',
    comfortHelp: 'Comfort uses temperature 42%, weather 28%, humidity 20%, and a 10% base score, then subtracts rain and max wind penalties. Higher is better for outdoor comfort.'
  }
};
