/**
 * 文件说明: 定义天气工具 React 面板共享的中英文文案。
 * 对应文档: docs/product-design.md
 */

export const dashboardCopy = {
  zh: {
    title: {
      cityFinder: '按天气找城市',
      weatherMap: '全球天气地图'
    },
    filterPanel: '天气筛选',
    resultPanel: '天气结果',
    forecastPanel: '选中城市天气',
    mapPanel: '地图',
    language: 'English',
    region: '地区',
    subRegion: '省份/州',
    time: '时间',
    nextDays: (days: number) => `未来 ${days} 天`,
    date: '日期',
    layer: '图层',
    quickFilters: '快速筛选',
    temperature: '气温',
    weather: '天气',
    humidity: '湿度',
    elevation: '海拔',
    all: '全部',
    sort: '排序',
    sortAscending: '升序',
    sortDescending: '降序',
    coverageRegions: '覆盖区域',
    coverageCities: '覆盖城市',
    citySamples: '城市样本',
    highMatchCities: '高匹配城市',
    citySearch: '搜索城市',
    citySearchPlaceholder: '搜索城市',
    noCityMatches: '没有匹配城市',
    loadingWeatherData: '正在加载天气数据',
    noForecastData: '暂无城市天气',
    noMapData: '暂无地图数据',
    suitableDays: (match: number, total: number) => `${match}/${total} 天适合`,
    average: '平均',
    dryDays: (days: number) => `少雨 ${days} 天`,
    humidityValue: (value: string) => `湿度 ${value}`,
    forecastHumidity: '湿度',
    forecastPrecipitation: '雨量',
    forecastPrecipitationProbability: '雨率',
    forecastWind: '风力',
    minTemperature: '最低温度',
    maxTemperature: '最高温度',
    minHumidity: '最低湿度',
    maxHumidity: '最高湿度',
    minElevation: '最低海拔',
    maxElevation: '最高海拔',
    precipitation: (value: number) => `降水 ${value} mm`
  },
  en: {
    title: {
      cityFinder: 'Find cities by weather',
      weatherMap: 'World weather map'
    },
    filterPanel: 'Weather filters',
    resultPanel: 'Weather results',
    forecastPanel: 'Selected city forecast',
    mapPanel: 'Map',
    language: '中文',
    region: 'Region',
    subRegion: 'State/province',
    time: 'Time',
    nextDays: (days: number) => `Next ${days} days`,
    date: 'Date',
    layer: 'Layer',
    quickFilters: 'Quick filters',
    temperature: 'Temperature',
    weather: 'Weather',
    humidity: 'RH',
    elevation: 'Elevation',
    all: 'All',
    sort: 'Sort',
    sortAscending: 'Ascending',
    sortDescending: 'Descending',
    coverageRegions: 'Regions',
    coverageCities: 'Cities',
    citySamples: 'City samples',
    highMatchCities: 'High matches',
    citySearch: 'Search cities',
    citySearchPlaceholder: 'Search city',
    noCityMatches: 'No matching cities',
    loadingWeatherData: 'Loading weather data',
    noForecastData: 'No city forecast',
    noMapData: 'No map data',
    suitableDays: (match: number, total: number) => `${match}/${total} suitable`,
    average: 'Avg',
    dryDays: (days: number) => `${days} low-rain days`,
    humidityValue: (value: string) => `RH ${value}`,
    forecastHumidity: 'RH',
    forecastPrecipitation: 'PCPN',
    forecastPrecipitationProbability: 'POP',
    forecastWind: 'WSPD',
    minTemperature: 'Minimum temperature',
    maxTemperature: 'Maximum temperature',
    minHumidity: 'Minimum RH',
    maxHumidity: 'Maximum RH',
    minElevation: 'Minimum elevation',
    maxElevation: 'Maximum elevation',
    precipitation: (value: number) => `Rainfall ${value} mm`
  }
};
