hosts:
  production-host:
    ssh:
      target: racknerd-us4g
    appDir: /var/www/weather-trip
    rsync:
      - package.json
      - package-lock.json
      - ecosystem.config.cjs
      - packages/weather-core/package.json
      - packages/weather-core/dist/
      - packages/weather-db/package.json
      - packages/weather-db/dist/

services:
  weather-trip-web:
    host: production-host
    rsync:
      - apps/web/package.json
      - apps/web/dist/
      - apps/web/.env.production
    npmInstall: true
    pm2Restart: true
    postCommand: []

  weather-trip-worker:
    host: production-host
    rsync:
      - apps/worker/package.json
      - apps/worker/dist/
      - apps/worker/.env.production
    npmInstall: true
    pm2Restart: true
    postCommand: []
